"""add gps Hostory event id

Revision ID: 5abfebad0815
Revises: 8126ae5ea89c
Create Date: 2026-06-11 21:55:48.156632

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5abfebad0815"
down_revision: Union[str, Sequence[str], None] = "8126ae5ea89c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gps_location_history",
        sa.Column("event_id", sa.String(length=100), nullable=True),
    )
    op.create_index(
        op.f("ix_gps_location_history_event_id"),
        "gps_location_history",
        ["event_id"],
        unique=True,
        mssql_where=sa.text("event_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_gps_location_history_event_id"), table_name="gps_location_history"
    )
    op.drop_column("gps_location_history", "event_id")
    # ### end Alembic commands ###
