"""add gps event id

Revision ID: 8126ae5ea89c
Revises: 94042e1a98bb
Create Date: 2026-06-11 21:44:08.756833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8126ae5ea89c'
down_revision: Union[str, Sequence[str], None] = '94042e1a98bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps_locations', sa.Column('event_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_gps_locations_event_id'), 'gps_locations', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gps_locations_event_id'), table_name='gps_locations')
    op.drop_column('gps_locations', 'event_id')
    # ### end Alembic commands ###
